### ISSUE TITLE
Configurable stylesheets

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-sample#1]
As document attribute:

> Some more companies will use this structure, but what's the best way of tailoring the design?
> Tailor the design — I just meant the branding. So the style sheet. Can I use a custom style sheet for different companies?

> Oh and we need to change names too. So maybe a customization YAML will best serve this

> True, I was thinking a light handed approach like just having a stylesheet and a YAML file with one of the gems we have is enough

> So maybe "metanorma-[brand]" is good enough

**Comment by opoudjis** [comment]
@ronaldtse I'm assuming that the new metanorma-acme repository is meant to supplant this repository?

**Comment by opoudjis** [comment]
isodoc explicitly takes stylesheets as parameters. I'm going to permit this in metanorma-acme to propagate up to asciidoctor input; but I will not allow it for the existing standards, because fixing their rendering is part of their point.

**Comment by ronaldtse** [comment]
@opoudjis yes, it's supposed to be the successor of this repo.

**Comment by opoudjis** [comment]
Done in metanorma-acme

**Comment by opoudjis** [comment]
I haven't provided the YAML, but I don't see what value it would add. Any references to the company name Acme are meant to be in the Coverpage HTML, which the user is supplying anyway; they will just type Acme in the cover page HTML, just as we typed Ribose in the RSD coverpage HTML.

**Comment by ronaldtse** [comment]
Coming back to this question.  It trying to beat a dead horse, but the way it works in Relaton-CLI to customize each entry and the index works well. 

So maybe this is what’s all needed to customize for people who don’t need to customize the schema?

**Comment by opoudjis** [comment]
I do not understand what you are asking for, and I am disinclined to. The Liquid templates for title page and intro page are already there in Acme. Whatever the schema customisation might be is nothing to do with Liquid, since it would involve custom text elements like `pre`, not metadata fields which are already catered for in metadata.rb.

If you're somehow asking for custom name elements like you've done in code under metanorma/acme.rb:

````
module Metanorma
  module Acme

    ORGANIZATION_NAME_SHORT = "Acme"
    ORGANIZATION_NAME_LONG = "Acme Corp."
    DOCUMENT_NAMESPACE = "https://open.ribose.com/standards/acme"

  end
end
````

---- then I still don't see why users shouldn't just type this straight into the Liquid template for the frontispiece. And if you want me to make this YAML anyway, this is low priority. Meaning it will be six months before I get to it.

**Comment by ronaldtse** [comment]
Yes, just putting them in the Liquid template works. What I’m saying is not everyone needs a customized XML schema. Some may want to just use a general schema but change the presentation. If the current implementation already supports that, there’s nothing that needs to be done.

**Comment by opoudjis** [comment]
The schema really is just for validation; so long as the code understands the elements in the document, and propagates them into metadata and the isodoc renderings, the schema can lag. They'll just get obsolete warnings.
